### ISSUE TITLE
Could not resolve '../common/Renderer.js' from src/renderers/webgpu/WebGPURenderer.js

### ISSUE THREAD

**Issue by AdrianScott** [danrossi/three-webgpu-renderer#1]
Love what you are doing here

This is an error I'm getting when I do "npm run build" on MacOS, also on Ubuntu, any ideas? Thanks!!

maybe refers to three.js: examples/jsm/renderers/common/Renderer.js
https://github.com/mrdoob/three.js/blob/e6f7c4e677cb8869502739da2640791d020d8d2f/examples/jsm/renderers/common/Renderer.js
 
/Renderer.js

> three-webgpu-renderer@0.153.0 build
> rollup -c rollup.config.js

./webgpu-renderer.js → build/webgpu-renderer.module.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
nodes/Nodes (imported by webgpu-renderer.js)
[!] Error: Could not resolve '../common/Renderer.js' from src/renderers/webgpu/WebGPURenderer.js

**Comment by AdrianScott** [comment]
ah, looks like needed 
git submodule init
git submodule update

**Comment by danrossi** [comment]
I made a mess of the submodule I added my fork with the renderer fix. But there is issues getting it merged so I have the renderer resolving locally. So I added it back to the main branch, it should be checking out dev ?  Then the rollup includes plugin will resolve the other includes from three. 

This is the resolve paths

https://github.com/danrossi/three-webgpu-renderer/blob/master/rollup.config.js#LL15C5-L15C127

**Comment by danrossi** [comment]
There is a performance problem on Windows I wonder what cpu usage it says for macOS ? The WebXRManager is non existent for this renderer still. 

It's a drop in replacement so you just do this to support both renderers. 

https://github.com/danrossi/three-webgpu-renderer/blob/master/tests/webgpu_video_panorama_equirectangular.html#L131

**Comment by AdrianScott** [comment]
beautiful, i think i figured out how to use it all now, thanks. hope to publish a sample proj in the next 2-3 days which should help more people as well...

**Comment by AdrianScott** [comment]
(not sure how to run the tests yet, but am able to use the module in a new vite project i set up w/ spinning cube, got the file refs and locations working)

**Comment by danrossi** [comment]
```
http-server ./
```
in the root you should be able to load the test files and it imports the files correctly. 

I've updated the build to get changes from three. I've updated the readme how to install into your own project via npm. You can use rollup location plugin to resolve an import to the bundle with three in it also. 

I've been working on performance fixes and I've changed the webgl option to fix a performance issue with video textures but there is still one for webgpu with video textures. In the webgpu test it loads either renderer, configures the required material and changes the required colorspace. 

So its all working now ?

**Comment by danrossi** [comment]
Check my rollup change for packaging a minified iife package. Which will be the end bundle result. Terser was completely removing some class names and needed to be filtered. It will cause immediate errors as nodes are being loaded just in time all of them. I see the renderer has to go through some improvements. I am trying to get cpu performance with video addressed and found another bug trying to cache shaders. Pull request method is slow so no idea how to resolve them other than duplicating the code into this repository.

**Comment by AdrianScott** [comment]
Hi - thanks for the project updates! I got one project working. Now i'm doing a new project that's more advanced w/ three.js. I'm getting this error, which I haven't looked into in detail yet, as I'm just updating that project from webgl to use webgpu: "Error: NodeMaterial: Material "MeshLambertMaterial" is not compatible."

I'm also trying to set up a new project using the new instructions, but the "npm install --save-dev danrossi/three-webgpu-renderer.git" (tried a few variations) just seems to hang... Anyhow I will keep playing around with a few possibilities.

**Comment by danrossi** [comment]
Not all of them are compatible. Because it's not added in. But when trying to hack in RawShaderMaterial the shader doesn't convert to webgpu. You have to make a ticket with three. But there is a way to add it in by making a local copy of Nodes.js and importing the material you need. It has to be imported into this but a copy made locally into src/nodes. 

It's still early days with this renderer and there is no webxr support for webgpu yet and api is still theoretical. I was hoping to still use it for video grid render but still dealing with video texture performance issue with a bug in it. 

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/nodes/Nodes.js
and make a copy of this to base from. https://github.com/mrdoob/three.js/blob/dev/examples/jsm/nodes/materials/MeshPhongNodeMaterial.js

Terser is missing alot of these import names when mangling so many need to be excluded. I've added in everything I found when minifying. My end bundles are always usually iife so they drop in without any user requirement for inline code. But three want to make people import modules for their project bundle which makes it hard to deliver. Why I had to make copies of the renderer to fix a top level async issue.

**Comment by danrossi** [comment]
I've bundled it into this project which shows iife usage with a global namespace. I'm looking at ways to have exported global namespace for bundles as modules so that we can then deprecate iife/umd. Can't use it yet because of performance issues. 

https://github.com/danrossi/three-troika/blob/main/test/index.html#L454

**Comment by danrossi** [comment]
Did you need me to make a bundle with that material added. I am not sure if it will render. I'd need an example for it. I'd have to make it a seperate module.

**Comment by AdrianScott** [comment]
Neat thanks, this is helpful, I'll play around with this feedback. My main goal is to make something cool with webgpu only as a bit of a showcase of webgpu, so I can limit what three.js stuff i use in it potentially.

**Comment by danrossi** [comment]
The overrides is not working yet like it did before I may have to include copies of multiple files.

**Comment by danrossi** [comment]
overrides dont resolve correctly. without having to copy alot of files. Will figure something out.

**Comment by AdrianScott** [comment]
ok thanks

**Comment by AdrianScott** [comment]
btw, are you on twitter? may be easier to chat there briefly, @adrianscottcom

**Comment by danrossi** [comment]
I do but don't use it. I had custom materials importing before but imports got changed. I'm not sure how to properly integrate that material. You might have to make a ticket with three to add it in.

**Comment by AdrianScott** [comment]
Thanks. I'm using the webgpu-renderer.module.js with no direct problems. I was using GLTF loader for a glb file w/ webgl but that's not working for me on webgpu, so i swapped that object out for one made of boxes etc in three.js and that is working fine. But I only have MeshBasicMaterial working on the new object which doesn't get affected by lighting, so yes if you have any way that'll let me use MeshPhongNodeMaterial, that'd be amazing. I'm not totally clear on how to do that from what you mentioned above. I think I have enough webgpu support with everything else to get this out the door.

**Comment by AdrianScott** [comment]
```
import * as THREE from 'three';
import { WebGPU, WebGPURenderer, texture, equirectUV } from './webgpu-renderer.module.js';

let renderer;

init();

async function init() {

if (await WebGPU.isAvailable()) {
 console.log("using WebGPU");
 renderer = new WebGPURenderer();
}
else {
 console.log("WebGPU not available; please use a browser with WebGPU support");
 return;
}

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

//const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

const geometry = new THREE.BoxGeometry( 1, 1, 1 );
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
const cube = new THREE.Mesh( geometry, material );
scene.add( cube );

camera.position.z = 5;

function animate() {
	requestAnimationFrame( animate );

	cube.rotation.x += 0.01;
	cube.rotation.y += 0.01;

	renderer.render( scene, camera );
}

animate();
}


```(but w/ MeshPhongNodeMaterial)

**Comment by danrossi** [comment]
What is it do you need ? other materials have to be added like this. A ticket with three might be able to get it in. I dont know what is required to implement it. 

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/nodes/materials/MeshPhongNodeMaterial.js
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/nodes/materials/MeshPhysicalNodeMaterial.js

**Comment by AdrianScott** [comment]
ok, thanks, understood. thank you!

**Comment by danrossi** [comment]
It seems how they set it up, it will load a heap of "nodes" on startup. Regardless what renderer is used. I'm not sure how to reduce that yet. I was trying to prevent copying too many files required to override imports as it becomes out of sync. 

Im pretty sure the properties of that material require special requirements for the renderer.

**Comment by danrossi** [comment]
Closing but I am still trying to work on the video texture performance issue, there is multiple video texture performance issues and have to use this project as its base for testing..

**Comment by AdrianScott** [comment]
Thanks for all of the help, Dan, we were able to get this published onto the Bitcoin blockchain. Looks like it's the first Ordinals/NFT collection using WebGPU, built on top of Three.js and the work of many great folks: https://ordinals.com/content/7dbc067eb7a692c9811cbff25b23ef82b4329cbcc2b729d05f493db887a19744i0

(hit 'm' to start the spatial audio, lots of other keys do things; more info https://twitter.com/Anarkoic/status/1684370030060769282 )

**Comment by danrossi** [comment]
It's ok. I just made another build change to use the unmodified renderer source. I'm trying to figure out hacks for an iife build another way. Which isn't working yet.

**Comment by danrossi** [comment]
I found an iife bundle work around. So update the upstream it will keep the renderer up to date with whats in three dev.
