### ISSUE TITLE
Black screen in v162

### ISSUE THREAD

**Issue by andreasrosdalw** [danrossi/three-webgpu-renderer#12]
I just updated from r161 to r162, and now the canvas is black, and there are no error messages in the javascript console.
I will try to find out what causes this, I just would like to report. So something is different in r162.
Can be tested here: https://www.fciv.net/?webgpu=true

This is for this project: https://github.com/fciv-net/fciv-net

**Comment by danrossi** [comment]
It seems to be fine in the demo. How do you set it up the nodes system or wgsl ? 

https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_video_panorama_equirectangular.html
https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_equirectangular.html

It even works with my modified sdf font package

https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_gl_text.html

**Comment by danrossi** [comment]
They have made a module build for this now I believe. I haven't had the time to check. If it needs further customisation for iife packages I'll look into it. It won't work by default in iife packages I have a special build for that.
