### ISSUE TITLE
install on project hangs

### ISSUE THREAD

**Issue by AdrianScott** [danrossi/three-webgpu-renderer#5]
I'm also trying to set up a new project using the new instructions, but the "npm install --save-dev danrossi/three-webgpu-renderer.git" (tried a few variations) just seems to hang...

**Comment by danrossi** [comment]
It's 

```
npm install https://github.com/danrossi/three-webgpu-renderer.git --save-dev
```

**Comment by danrossi** [comment]
Example

https://github.com/danrossi/three-troika/blob/main/package.json#L20

**Comment by AdrianScott** [comment]
same behavior for me, just hangs (no need to include github.com in recent npm versions, fyi)

tried creating a new proj with that package.json of yours and getting errors 

377 error code 128
378 error An unknown git error occurred
379 error command git --no-replace-objects clone ssh://git@github.com/danrossi/three-webgpu-renderer.git /home/user/.npm/_cacache/tmp/git-cloneBshuAw --recurse-submodules --depth=1
380 error fatal: destination path '/home/user/.npm/_cacache/tmp/git-cloneBshuAw' already exists and is not an empty directory.
381 verbose exit 128

will see what else i can try, thanks

**Comment by danrossi** [comment]
its because you need a github ssh key loaded for ssh checkout. I've added an example project directory. Just run this and it will checkout via https. 

```
npm install
```

**Comment by danrossi** [comment]
Does that example project package help ? It should check out https not ssh.
