### ISSUE TITLE
three bundle doesn't export all nodes exports

### ISSUE THREAD

**Issue by danrossi** [danrossi/three-webgpu-renderer#6]
Include all nodes exports to be usable in setting up shaders.

**Comment by C0DESTR0NG** [comment]
Hey @danrossi! Sorry to connect via your closed issue, but trying (unsuccessfully) reach you via github and beyond… Can I reach you directly via X or email? Would love to pick your brain about a threejs + webxr + Vision Pro topic I'm exploring.

**Comment by danrossi** [comment]
What do you need to know ? I am working on integrating hand tracking in my feature but just figured out the simulator has no VR controller inputs at all and no hand tracking support. So can't test anything. I have thumbstick controller updating rotation offsets of the headset now so no need for head turning. Just figured it out.

**Comment by danrossi** [comment]
I've updated my profile with my email

**Comment by C0DESTR0NG** [comment]
> I've updated my profile with my email

Thanks again – I fired an email your way 💪🏼
