### ISSUE TITLE
Crash in WebGPU: Error: no matching constructor for vec4

### ISSUE THREAD

**Issue by andreasrosdalw** [danrossi/three-webgpu-renderer#7]
I still get a crash in WebGPU, even with the fix in #6. 

To reproduce, start a new game, then type /observe (+Enter) into the game console after it has started.
https://www.fciv.net/?webgpu=true

Here is the commit which includes the fix in #6:
https://github.com/fciv-net/fciv-net/commit/192930a84e837ece0a208dcc975c3b3b96694b8b

Screenshot:
![image](https://github.com/danrossi/three-webgpu-renderer/assets/41650711/f0227ff4-2015-476b-ae45-6142fded694c)

The error is not present in the normal Three.js build, and the error is not present when using three-webgpu-renderer with the WebGL backend in Firefix.

Operating system: Windows 11
Browser: Google Chrome

**Comment by danrossi** [comment]
It looks like you are using wgsl. Perhaps make a ticket in three. its not the bundle or module. It's your wgsl code.

**Comment by andreasrosdalw** [comment]
I created a ticket in Three.js. Note that I am not using any custom wgsl shaders, in this version it's only high-level Three.js JavaScript and three-webgpu-renderer.  Thank you.

**Comment by andreasrosdalw** [comment]
The error message is about the variable **DiffuseColor**, and that there is some exception assigning this variable.

DiffuseColor is for example mentioned here in the Three.js source code:
https://github.com/mrdoob/three.js/blob/master/examples/jsm/nodes/core/PropertyNode.js#L40

**Comment by andreasrosdal** [comment]
> I'm sorry mate it's mine. You can fork and run the build yourself. I try to check in and keep it up to date. But to be absolutely honest I am personally having issues finding regular customers right now and issues at home to keep up with this.

Please e-mail me at andreas.rosdal (at) gmail, thank you.

**Comment by danrossi** [comment]
Ive updated the build
